### PR TITLE
Restore incremental build functionality of MSBuild/VS

### PR DESCRIPTION
**Pull request by BMurri**

### CODE REVIEW

**Comment by ursenzler** [comment]
I'll be back from vacation next week. Thanks!

**Comment by ursenzler** [comment]
Can you please describe what problem this solves? And how you solved it?

I want to reproduce the problem (and its solution) before merging your changes into master.

**Comment by BMurri** [comment]
Before adding this versioning tool to a solution, build a large multi-project solution with intra-solution project references. Then immediately after it finishes, build again. The second build runs and completes quickly, without rewriting the output binaries. Incorporate your system and repeat the above two builds. Note that, without any changes or commits, even single project solutions using your system rebuilds the outputs binaries every single time.

Better yet: include packaging projects in the above solution using your system, and setup remote debugging. After a build, install the package on the remote system. Hit F5 after you install the produced package and observe that none of your breakpoints are honored, because the running binaries no longer match the remote system.

Observe how, with my fix, neither of the above observed problems occurs. Now, you have faster builds during debugging sessions, and remote debugging sessions aren't broken (unless you changed a file somewhere and forgot to reinstall).

Now, commit your bug fix (without having made any file changes) and build again. Notice that the output binaries have been rewritten (and the version is different, as desired).

**Comment by BMurri** [comment]
What I don't know is if a tweak is needed to accommodate pull request #12 or not (should file version be added to the embedded json/test for equality or not)? I would assume so.

**Comment by BMurri** [comment]
How this solves the issue us it now creates exactly one generated version source file per project (instead of one per project per build). That file is checked during build to ensure it's not obsolete. If it's missing or obsolete, it's (re)written. If not, it's left alone.

**Comment by ursenzler** [comment]
@BMurri I finally found the time to merge your PR. I added the FileVersion (from PR #12 ) accordingly and removed some unused (I think so) code.
Could you please review my changes and see if they make sense for you? Thanks.
Once reviewed I'll publish the new version to nuget-org. At the moment, the merged version is available from the MyGet feed https://www.myget.org/F/appccelerate/api/v3/index.json

**Pull request merged**
